import "./globals.css";
import { Inter,Raleway } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const raleway = Raleway({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.className} ${raleway.className}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
